FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        debhelper \
        devscripts \
        dh-apparmor \
        dpkg-dev \
        equivs \
        fakeroot \
        git \
        libapparmor-dev \
        libaudit-dev \
        libblkid-dev \
        libcap-ng-dev \
        libcurl4-gnutls-dev \
        libdevmapper-dev \
        libfuse3-dev \
        libglib2.0-dev \
        libgnutls28-dev \
        libiscsi-dev \
        libnl-3-dev \
        libnl-route-3-dev \
        libnuma-dev \
        libparted-dev \
        libpciaccess-dev \
        librbd-dev \
        libreadline-dev \
        libsasl2-dev \
        libselinux1-dev \
        libssh-dev \
        libssh2-1-dev \
        libtirpc-dev \
        libudev-dev \
        libxml2-dev \
        meson \
        ninja-build \
        pkgconf \
        python3-docutils \
        python3-pytest \
        python3-setuptools \
        qemu-utils \
        xsltproc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
