FROM almalinux:9

RUN dnf install -y dnf-plugins-core \
    && dnf config-manager --set-enabled crb \
    && dnf install -y \
        findutils \
        git \
        libxslt \
        make \
        meson \
        ninja-build \
        python3 \
        rpm-build \
        rpmdevtools \
    && dnf clean all

WORKDIR /work
